"""Workspace inventory and evidence-backed Qualcomm AI Hub report endpoints."""
import json, os, uuid, tempfile
from datetime import datetime, timezone
from flask import Blueprint, current_app, jsonify, request, abort, g
from app.models import db, Project, Document, Claim, Evidence, RiskFinding

runtime_bp = Blueprint("runtime", __name__, url_prefix="/api/runtime")

@runtime_bp.route("/workspace", methods=["GET"])
def workspace_summary():
    pid = request.args.get("project_id", type=int)
    if not pid or not db.session.get(Project, pid): abort(400, description="Valid project_id is required.")
    docs = Document.query.filter_by(project_id=pid).all(); claims = Claim.query.join(Document).filter(Document.project_id == pid).all()
    return jsonify({"project_id": pid, "documents": len(docs), "processed_documents": sum(d.status == "ready" for d in docs), "failed_documents": sum(d.status == "failed" for d in docs), "claims": len(claims), "evidence": Evidence.query.filter_by(project_id=pid).count(), "findings": RiskFinding.query.filter_by(project_id=pid).count(), "metrics": {m: sum(c.metric_type == m for c in claims) for m in ("revenue", "customer_count", "market_size")}}), 200


@runtime_bp.route("/npu-report", methods=["GET"])
def get_npu_report():
    """Return the most recently imported Qualcomm AI Hub report, if present."""
    folder = os.path.join(current_app.instance_path, "npu_reports", f"user-{g.user.id}")
    latest_path = os.path.join(folder, "latest.json")
    if not os.path.isfile(latest_path):
        return jsonify({"available": False, "report": None}), 200
    try:
        with open(latest_path, encoding="utf-8") as f:
            report = json.load(f)
    except (OSError, ValueError):
        abort(500, description="Saved NPU report could not be read.")
    return jsonify({"available": True, "report": report}), 200


@runtime_bp.route("/npu-report", methods=["POST"])
def import_npu_report():
    """Import a real report JSON produced by tools/qaihub_npu/run_npu_smoke_test.py."""
    data = request.get_json(silent=True) or {}
    report = data.get("report")
    if not isinstance(report, dict):
        abort(422, description="Provide a report JSON object. PDF, CSV, and XLSX files are not validation reports.")
    required = ("product", "test_scope", "device_requested", "overall_status", "checks", "job_ids")
    missing = [key for key in required if key not in report]
    if missing:
        abort(422, description="This is not a complete FoundRisk Qualcomm AI Hub report. Missing required fields: " + ", ".join(missing) + ". Financial test-data JSON belongs in Documents/Analysis, not Runtime Benchmarks.")
    if not isinstance(report.get("checks"), dict) or not isinstance(report.get("job_ids"), dict):
        abort(422, description="Report fields 'checks' and 'job_ids' must be JSON objects.")
    if report.get("product") != "FoundRisk Edge — Qualcomm AI Hub NPU smoke test":
        abort(422, description="This report was not generated by the FoundRisk Qualcomm AI Hub test tool.")
    if report.get("overall_status") not in ("PASS", "FAIL", "ERROR"):
        abort(422, description="Report overall_status must be PASS, FAIL or ERROR.")
    folder = os.path.join(current_app.instance_path, "npu_reports", f"user-{g.user.id}")
    os.makedirs(folder, exist_ok=True)
    report["imported_at"] = datetime.now(timezone.utc).isoformat()
    path = os.path.join(folder, "latest.json")
    fd, temp_path = tempfile.mkstemp(prefix=".npu-report-", suffix=".tmp", dir=folder)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
            f.flush()
            os.fsync(f.fileno())
        os.replace(temp_path, path)
    except Exception:
        try: os.unlink(temp_path)
        except OSError: pass
        current_app.logger.exception("Could not persist imported NPU report")
        abort(500, description="NPU report could not be saved.")
    return jsonify({"saved": True, "imported_at": report["imported_at"], "overall_status": report["overall_status"]}), 201


# Hosted-device NPU report snapshots are stored separately from the latest imported report.
@runtime_bp.route("/npu-snapshots", methods=["GET"])
def list_npu_snapshots():
    pid = request.args.get("project_id", type=int)
    if not pid or not db.session.get(Project, pid):
        abort(400, description="Valid project_id is required.")
    folder = os.path.join(current_app.instance_path, "npu_snapshots")
    items = []
    if os.path.isdir(folder):
        for name in os.listdir(folder):
            if not name.endswith(".json"):
                continue
            try:
                with open(os.path.join(folder, name), encoding="utf-8") as f:
                    item = json.load(f)
                if int(item.get("project_id", -1)) != pid:
                    continue
                report = item.get("report") or {}
                items.append({
                    "snapshot_id": name[:-5], "filename": name,
                    "saved_at": item.get("saved_at"),
                    "device": report.get("device_requested", "Device not recorded"),
                    "status": report.get("overall_status", "Status not recorded"),
                    "runtime": report.get("target_runtime_requested", "Runtime not recorded"),
                })
            except (OSError, ValueError, TypeError):
                continue
    items.sort(key=lambda row: row.get("saved_at") or "", reverse=True)
    items = items[:50]
    return jsonify({"snapshots": items, "count": len(items), "latest_snapshot_id": items[0]["snapshot_id"] if items else None}), 200


@runtime_bp.route("/npu-snapshots", methods=["POST"])
def save_npu_snapshot():
    data = request.get_json(silent=True) or {}
    report = data.get("report")
    pid = data.get("project_id")
    try:
        pid = int(pid)
    except (TypeError, ValueError):
        abort(400, description="Valid project_id is required.")
    if not db.session.get(Project, pid):
        abort(404, description="Project not found.")
    if not isinstance(report, dict) or report.get("product") != "FoundRisk Edge — Qualcomm AI Hub NPU smoke test":
        abort(422, description="Import a valid FoundRisk Qualcomm AI Hub test report before saving a snapshot.")
    if report.get("overall_status") not in ("PASS", "FAIL", "ERROR"):
        abort(422, description="Report status must be PASS, FAIL or ERROR.")
    folder = os.path.join(current_app.instance_path, "npu_snapshots")
    os.makedirs(folder, exist_ok=True)
    snapshot_id = uuid.uuid4().hex
    saved_at = datetime.now(timezone.utc).isoformat()
    payload = {"snapshot_id": snapshot_id, "project_id": pid, "saved_at": saved_at, "report": report}
    path = os.path.join(folder, snapshot_id + ".json")
    fd, temp_path = tempfile.mkstemp(prefix=".npu-snapshot-", suffix=".tmp", dir=folder)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
            f.flush()
            os.fsync(f.fileno())
        os.replace(temp_path, path)
    except Exception:
        try:
            os.unlink(temp_path)
        except OSError:
            pass
        current_app.logger.exception("Could not persist NPU report snapshot")
        abort(500, description="NPU report snapshot could not be saved to the application data folder.")
    return jsonify({"snapshot_id": snapshot_id, "saved_at": saved_at, "filename": os.path.basename(path), "project_id": pid}), 201


@runtime_bp.route("/npu-snapshot/<snapshot_id>", methods=["GET"])
def get_npu_snapshot(snapshot_id):
    if not snapshot_id or any(ch not in "0123456789abcdef" for ch in snapshot_id.lower()):
        abort(404, description="Snapshot not found.")
    path = os.path.join(current_app.instance_path, "npu_snapshots", snapshot_id + ".json")
    if not os.path.isfile(path):
        abort(404, description="Snapshot not found.")
    try:
        with open(path, encoding="utf-8") as f:
            payload = json.load(f)
    except (OSError, ValueError):
        abort(500, description="Saved NPU report snapshot could not be read.")
    return jsonify({"snapshot": payload}), 200
